// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.2.1
// Schema file: DeviceConfiguration.xsd
// Creation Date: 2006-06-06 20:56:04
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections.Generic;
using System.Xml.Schema;
using System.ComponentModel;

namespace Notpod.Configuration12
{

    public class DeviceConfiguration
    {

        private ICollection<SyncPattern> syncPatterns = new List<SyncPattern>();

        private ICollection<Device> devices = new List<Device>();

        /// <summary>
        /// Accessor for syncPatterns.
        /// </summary>
        public SyncPattern[] SyncPatterns
        {
            get
            {
                SyncPattern[] patterns = new SyncPattern[syncPatterns.Count];
                syncPatterns.CopyTo(patterns, 0);
                return patterns;
            }
            set
            {
                syncPatterns.Clear();
                foreach (SyncPattern sp in value)
                    syncPatterns.Add(sp);
            }
        }

        /// <summary>
        /// Accessor for devices.
        /// </summary>
        public Device[] Devices
        {
            get
            {

                Device[] devicesarr = new Device[devices.Count];
                devices.CopyTo(devicesarr, 0);
                return devicesarr;

            }
            set
            {
                devices.Clear();
                foreach (Device d in value)
                    devices.Add(d);

            }
        }
        
        /// <summary>
        /// Add a device.
        /// </summary>
        /// <param name="d">Device to add.</param>
        public void AddDevice(Device d)
        {
            devices.Add(d);
        }

        /// <summary>
        /// Remove a Device.
        /// </summary>
        /// <param name="d">Device to remove.</param>
        /// <returns></returns>
        public bool RemoveDevice(Device d)
        {
            return devices.Remove(d);
        }

        /// <summary>
        /// Add a SyncPattern.
        /// </summary>
        /// <param name="sp">SyncPattern sp</param>
        public void AddSyncPattern(SyncPattern sp)
        {
            syncPatterns.Add(sp);
        }
                
        /// <summary>
        /// Remove a SyncPattern.
        /// </summary>
        /// <param name="sp">SyncPattern to remove.</param>
        /// <returns></returns>
        public bool RemoveSyncPattern(SyncPattern sp)
        {
            return syncPatterns.Remove(sp);
        }

    }

    //public struct Declarations
    //{
    //    public const string SchemaVersion = "";
    //}


    //[Serializable]
    //[EditorBrowsable(EditorBrowsableState.Advanced)]
    //public class DeviceCollection : ArrayList
    //{
    //    public Device Add(Device obj)
    //    {
    //        base.Add(obj);
    //        return obj;
    //    }

    //    public Device Add()
    //    {
    //        return Add(new Device());
    //    }

    //    public void Insert(int index, Device obj)
    //    {
    //        base.Insert(index, obj);
    //    }

    //    public void Remove(Device obj)
    //    {
    //        base.Remove(obj);
    //    }

    //    new public Device this[int index]
    //    {
    //        get { return (Device) base[index]; }
    //        set { base[index] = value; }
    //    }
    //}

    //[Serializable]
    //[EditorBrowsable(EditorBrowsableState.Advanced)]
    //public class SyncPatternCollection : ArrayList
    //{
    //    public SyncPattern Add(SyncPattern obj)
    //    {
    //        base.Add(obj);
    //        return obj;
    //    }

    //    public SyncPattern Add()
    //    {
    //        return Add(new SyncPattern());
    //    }

    //    public void Insert(int index, SyncPattern obj)
    //    {
    //        base.Insert(index, obj);
    //    }

    //    public void Remove(SyncPattern obj)
    //    {
    //        base.Remove(obj);
    //    }

    //    new public SyncPattern this[int index]
    //    {
    //        get { return (SyncPattern) base[index]; }
    //        set { base[index] = value; }
    //    }
    //}



    //[XmlRoot(ElementName="DeviceConfiguration",IsNullable=false),Serializable]
    //public class DeviceConfiguration
    //{

    //    [XmlElement(Type=typeof(SyncPatterns),ElementName="SyncPatterns",IsNullable=false,Form=XmlSchemaForm.Qualified)]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public SyncPatterns __SyncPatterns;

    //    [XmlIgnore]
    //    public SyncPatterns SyncPatterns
    //    {
    //        get
    //        {
    //            if (__SyncPatterns == null) __SyncPatterns = new SyncPatterns();		
    //            return __SyncPatterns;
    //        }
    //        set {__SyncPatterns = value;}
    //    }

    //    [XmlElement(Type=typeof(Devices),ElementName="Devices",IsNullable=false,Form=XmlSchemaForm.Qualified)]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public Devices __Devices;

    //    [XmlIgnore]
    //    public Devices Devices
    //    {
    //        get
    //        {
    //            if (__Devices == null) __Devices = new Devices();		
    //            return __Devices;
    //        }
    //        set {__Devices = value;}
    //    }

    //    public DeviceConfiguration()
    //    {
    //    }
    //}


    //[XmlType(TypeName="SyncPatterns"),Serializable]
    //public class SyncPatterns
    //{
    //    [System.Runtime.InteropServices.DispIdAttribute(-4)]
    //    public IEnumerator GetEnumerator() 
    //    {
    //        return SyncPatternCollection.GetEnumerator();
    //    }

    //    public SyncPattern Add(SyncPattern obj)
    //    {
    //        return SyncPatternCollection.Add(obj);
    //    }

    //    [XmlIgnore]
    //    public SyncPattern this[int index]
    //    {
    //        get { return (SyncPattern) SyncPatternCollection[index]; }
    //    }

    //    [XmlIgnore]
    //    public int Count 
    //    {
    //        get { return SyncPatternCollection.Count; }
    //    }

    //    public void Clear()
    //    {
    //        SyncPatternCollection.Clear();
    //    }

    //    public SyncPattern Remove(int index) 
    //    { 
    //        SyncPattern obj = SyncPatternCollection[index];
    //        SyncPatternCollection.Remove(obj);
    //        return obj;
    //    }

    //    public void Remove(object obj)
    //    {
    //        SyncPatternCollection.Remove(obj);
    //    }

    //    [XmlElement(Type=typeof(SyncPattern),ElementName="SyncPattern",IsNullable=false,Form=XmlSchemaForm.Qualified)]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public SyncPatternCollection __SyncPatternCollection;

    //    [XmlIgnore]
    //    public SyncPatternCollection SyncPatternCollection
    //    {
    //        get
    //        {
    //            if (__SyncPatternCollection == null) __SyncPatternCollection = new SyncPatternCollection();
    //            return __SyncPatternCollection;
    //        }
    //        set {__SyncPatternCollection = value;}
    //    }

    //    public SyncPatterns()
    //    {
    //    }
    //}


    //[XmlType(TypeName="SyncPattern"),Serializable]
    //public class SyncPattern
    //{

    //    [XmlElement(ElementName="Identifier",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public string __Identifier;

    //    [XmlIgnore]
    //    public string Identifier
    //    { 
    //        get { return __Identifier; }
    //        set { __Identifier = value; }
    //    }

    //    [XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public string __Name;

    //    [XmlIgnore]
    //    public string Name
    //    { 
    //        get { return __Name; }
    //        set { __Name = value; }
    //    }

    //    [XmlElement(ElementName="Pattern",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public string __Pattern;

    //    [XmlIgnore]
    //    public string Pattern
    //    { 
    //        get { return __Pattern; }
    //        set { __Pattern = value; }
    //    }

    //    [XmlElement(ElementName="Description",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public string __Description;

    //    [XmlIgnore]
    //    public string Description
    //    { 
    //        get { return __Description; }
    //        set { __Description = value; }
    //    }

    //    [XmlElement(ElementName="CompilationsPattern",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public string __CompilationsPattern;

    //    [XmlIgnore]
    //    public string CompilationsPattern
    //    { 
    //        get { return __CompilationsPattern; }
    //        set { __CompilationsPattern = value; }
    //    }

    //    public SyncPattern()
    //    {
    //    }
    //}


    //[XmlType(TypeName="Devices"),Serializable]
    //public class Devices
    //{
    //    [System.Runtime.InteropServices.DispIdAttribute(-4)]
    //    public IEnumerator GetEnumerator() 
    //    {
    //        return DeviceCollection.GetEnumerator();
    //    }

    //    public Device Add(Device obj)
    //    {
    //        return DeviceCollection.Add(obj);
    //    }

    //    [XmlIgnore]
    //    public Device this[int index]
    //    {
    //        get { return (Device) DeviceCollection[index]; }
    //    }

    //    [XmlIgnore]
    //    public int Count 
    //    {
    //        get { return DeviceCollection.Count; }
    //    }

    //    public void Clear()
    //    {
    //        DeviceCollection.Clear();
    //    }

    //    public Device Remove(int index) 
    //    { 
    //        Device obj = DeviceCollection[index];
    //        DeviceCollection.Remove(obj);
    //        return obj;
    //    }

    //    public void Remove(object obj)
    //    {
    //        DeviceCollection.Remove(obj);
    //    }

    //    [XmlElement(Type=typeof(Device),ElementName="Device",IsNullable=false,Form=XmlSchemaForm.Qualified)]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public DeviceCollection __DeviceCollection;

    //    [XmlIgnore]
    //    public DeviceCollection DeviceCollection
    //    {
    //        get
    //        {
    //            if (__DeviceCollection == null) __DeviceCollection = new DeviceCollection();
    //            return __DeviceCollection;
    //        }
    //        set {__DeviceCollection = value;}
    //    }

    //    public Devices()
    //    {
    //    }
    //}


    //[XmlType(TypeName="Device"),Serializable]
    //public class Device
    //{

    //    [XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public string __Name;

    //    [XmlIgnore]
    //    public string Name
    //    { 
    //        get { return __Name; }
    //        set { __Name = value; }
    //    }

    //    [XmlElement(ElementName="MediaRoot",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public string __MediaRoot;

    //    [XmlIgnore]
    //    public string MediaRoot
    //    { 
    //        get { return __MediaRoot; }
    //        set { __MediaRoot = value; }
    //    }

    //    [XmlElement(ElementName="SyncPattern",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public string __SyncPattern;

    //    [XmlIgnore]
    //    public string SyncPattern
    //    { 
    //        get { return __SyncPattern; }
    //        set { __SyncPattern = value; }
    //    }

    //    [XmlElement(ElementName="RecognizePattern",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public string __RecognizePattern;

    //    [XmlIgnore]
    //    public string RecognizePattern
    //    { 
    //        get { return __RecognizePattern; }
    //        set { __RecognizePattern = value; }
    //    }

    //    [XmlElement(ElementName="Playlist",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public string __Playlist;

    //    [XmlIgnore]
    //    public string Playlist
    //    { 
    //        get { return __Playlist; }
    //        set { __Playlist = value; }
    //    }

    //    private ArrayList initialTracks = new ArrayList();

    //    public ArrayList InitialTracks
    //    {
    //        get { return initialTracks; }
    //    }

    //    public Device()
    //    {
    //    }
    //}
}
