// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.2.1
// Schema file: ItaConfiguration.xsd
// Creation Date: 2006-06-06 20:21:21
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Jaranweb.iTunesAgent
{

    //public struct Declarations
    //{
    //    public const string SchemaVersion = "";
    //}




    //[XmlRoot(ElementName="Configuration",IsNullable=false),Serializable]
    //public class Configuration
    //{

    //    [XmlElement(ElementName="ShowNotificationPopups",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="boolean")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public bool __ShowNotificationPopups;
		
    //    [XmlIgnore]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public bool __ShowNotificationPopupsSpecified;
		
    //    [XmlIgnore]
    //    public bool ShowNotificationPopups
    //    { 
    //        get { return __ShowNotificationPopups; }
    //        set { __ShowNotificationPopups = value; __ShowNotificationPopupsSpecified = true; }
    //    }

    //    [XmlElement(ElementName="DeviceConfiguration",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public string __DeviceConfiguration;
		
    //    [XmlIgnore]
    //    public string DeviceConfiguration
    //    { 
    //        get { return __DeviceConfiguration; }
    //        set { __DeviceConfiguration = value; }
    //    }

    //    [XmlElement(ElementName="UseListFolder",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="boolean")]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public bool __UseListFolder;
		
    //    [XmlIgnore]
    //    [EditorBrowsable(EditorBrowsableState.Advanced)]
    //    public bool __UseListFolderSpecified;
		
    //    [XmlIgnore]
    //    public bool UseListFolder
    //    { 
    //        get { return __UseListFolder; }
    //        set { __UseListFolder = value; __UseListFolderSpecified = true; }
    //    }

    //    public Configuration()
    //    {
    //    }
    //}
}
